-- MySQL Script generated by MySQL Workbench
-- Sat Sep  3 14:55:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog-ocr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog-ocr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog-ocr` DEFAULT CHARACTER SET utf8mb4 ;
USE `blog-ocr` ;

-- -----------------------------------------------------
-- Table `blog-ocr`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ocr`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` INT NOT NULL,
  `dateCreation` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-ocr`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ocr`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(100) NOT NULL,
  `chapo` VARCHAR(255) NOT NULL,
  `contenu` MEDIUMTEXT NOT NULL,
  `auteur` VARCHAR(100) NOT NULL,
  `dateCreation` VARCHAR(100) NOT NULL,
  `dateModif` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-ocr`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ocr`.`commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentaire` MEDIUMTEXT NOT NULL,
  `dateCreation` VARCHAR(100) NOT NULL,
  `estValide` TINYINT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-ocr`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ocr`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telephone` VARCHAR(100) NOT NULL,
  `objet` VARCHAR(255) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `dateCreation` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
